### ISSUE TITLE
Browserless 2 support

### ISSUE THREAD

**Issue by 4tolexx** [rubycdp/ferrum#501]
does ferrum have support for browserless version 2.

i am trying to migrate from selenium to cuprite. everything seems to be running fine using browserless/chrome version 1 in docker. i set it up following https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing

i have been trying to migrate to browserless chrome using pretty much the same setup but it does not work. below is my config using docker compose

```yml
 chrome:
    image: ghcr.io/browserless/chrome:latest
    ports:
      - 3000:3000
    environment:
      HEADLESS: false
      TIMEOUT: 600000
    shm_size: 512m
 ```

cuprite setup

```ruby
Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(
    app,
    **{
      url: 'http://chrome:3000',
      headless: ENV['HEADLESS'],
      process_timeout: 10,
      timeout: 30,
      window_size: [1920, 1080],
      browser_options: { 'no-sandbox': nil, 'disable-gpu': nil },
      save_path: DownloadHelper::PATH
    }
  )
end
```

i am getting the error:

```text
Errno::ECONNREFUSED:
            Connection refused - connect(2) for "0.0.0.0" port 3000
```

**Comment by jschroeder** [comment]
I am experiencing the same problem with a similar setup.

Difference: my `chrome` container is listening on port `9222` and I did not set `HEADLESS` to `false`. I am using `kamal 2` and the `kamal` docker network that comes with it. I am trying to run a raw Ferrum::Browser connection from my `rails` container to the `chrome` container instead of the additional `cuprite` layer.

Observations:
- from a shell in my `rails` container I am able to contact the `chrome` container's port 9222 (`curl "http://172.18.0.1:9222/sessions?token=x"` works nicely and returns the CDP sessions)
- starting a Ferrum::Browser `Ferrum::Browser.new(url: "http://172.18.0.1:9222")` on my `rails` container's Rails console returns the "Connection refused" message described by @4tolexx 
- watching the `chrome` container's output I can see that the `Ferrum::Browser.new` initially reaches the CDP instance in the `chrome` container, but fails where it is supposed to make a websocket connection
  ```
  browserless.io:server:trace  Handling inbound HTTP request on "GET: /json/version" +15s
  browserless.io:server:trace  Found matching HTTP route handler "/json/version?(/)" +1ms
  browserless.io:server:trace  Authorizing HTTP request to "/json/version" +0ms
  browserless.io:server:trace  HTTP connection complete +1ms
  ```
  The next line *should* be `browserless.io:server:trace  Handling inbound WebSocket request on "/" +99ms` but never shows.

Even more confusing: I am able to start `Ferrum::Browser.new(ws_url: 'ws://localhost:9222')` in my local workstation when I ssh into the docker host machine and tunnel port `9222` (`ssh -L 9222:localhost:9222 my_docker_host_ip`). This means the `chrome` container works, and Ferrum is able to talk to it, just not from container to container.

**Comment by jschroeder** [comment]
I am having the same issue.
I did find the cause of the problem in Ferrum v0.15.

When Ferrum establishes the connection to chrome in your `chrome` container, it first makes an HTTP call to the provided host/port to fetch some meta data (`Ferrum::Browser::Process#parse_json_version`). That meta data includes the actual `webSocketDebuggerUrl`, which Ferrum will try to utilize. But `Browserless 2` returns an incorrect value (host `0.0.0.0` instead of the original hostname). 
The subsequent websocket calls to that URL will fail, unless 0.0.0.0:9222 (or :3000 in your case) happens to be bound to the  `chrome` container's port.

It seems like that code has changed in `HEAD`, but I have not verified yet that it will work.

**Comment by leoc** [comment]
@jschroeder Thanks for the hint. I have used `ws_url: "ws://chrome:3333"` for the driver setup which should be the correct setup for my browserless container named `chrome` and the port set to `3333`.

Unfortunately I only receive `Browser is dead or given window is closed` from Ferrum.

Did you do something else to get it to work?

**Comment by jschroeder** [comment]
I certainly have seen your `DeadBrowserError` before, but not recently. `Browserless 2` disposes of sessions after 30 seconds, and it doesn't care if you interact with the session or not. 30 seconds after craetion it will dispose of them, and probably result in a `DeadBrowserError`. But I see that you extended your `TIMEOUT` already, so you are already aware of this.

Here are the seginificant parts of my kamal `deploy.yml` (it should look familiar to your setup:
```
service: my_app
require_destination: true
image: kamal-images/my_app

servers:
  job:
    hosts:
      - my_app.dev
    cmd: bundle exec good_job start
    env:
      CDP_WS_URL: ws://chrome:9222 # I am using that environment variable to establish a WS connection to Chrome

registry:  <snip>.....</snip>
ssh: <snip>.....</snip>

accessories:
  chrome:
    image: ghcr.io/browserless/chromium
    env:
      PORT: 9222
      TIMEOUT: 600000 # sessions live up to 10 minutes max
    roles:
      - job
```

Then, when I run a Rails console on the `job` container (e.g. via `kamal console -r job`), I can successfully call `Ferrum::Browser.new ws_url: ENV['CDP_WS_URL']`.
